
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tatakai Brawlers
 */
public class Menu extends javax.swing.JFrame {

    Choose chooseFrame = new Choose();
    Characters charFrame = new Characters();

    /**
     * Creates new form Main
     */
    public Menu() {
        initComponents();
    }

    public void initBrawlers() {
        String name = nameField.getText();
        //Polite Cat
        ArrayList<Power> politeList = new ArrayList();
        politeList.add(new Power("Say a compliment", 10, "Makes enemy blush, increased body temperature kills some of his cells.", 0.9));
        politeList.add(new Power("Apologize", -12, "Causes confusion to enemy because it hasn't done anything wrong", 0.7));
        BrawlerSys.addBrawler(new Player(name, "Polite cat", 100, "polite_cat.jpg", politeList));

        //Stuck Cat
        ArrayList<Power> stuckList = new ArrayList();
        stuckList.add(new Power("Pile up hatred", 11, "The more you think it's funny, the angrier it gets", 0.8));
        stuckList.add(new Power("Feel awkward", -8, "You feel so embarrassed by just looking at it.", 0.4));
        BrawlerSys.addBrawler(new Player(name, "Stuck cat", 100, "stuck_cat.jpg", stuckList));

        //Strong Cat
        ArrayList<Power> strongList = new ArrayList();
        strongList.add(new Power("Beat you to hell", 15, "It beats you so bad that even your mom can't recognize you.", 0.5));
        strongList.add(new Power("Flex", -9, "Weird flex but ok.", 0.9));
        BrawlerSys.addBrawler(new Player(name, "Strong cat", 100, "strong_cat.jpg", strongList));

        //Distorted Cat
        ArrayList<Power> distortedList = new ArrayList();
        distortedList.add(new Power("Shake off your eyeballs", 13, "It is the scariest thing you've ever seen in your life.", 0.3));
        distortedList.add(new Power("Get high", -10, "Probably had too much catnip.", 0.7));
        BrawlerSys.addBrawler(new Enemy("Distorted Cat", 100, "distorted_cat.jpg", distortedList));

        //Evil Cat
        ArrayList<Power> evilList = new ArrayList();
        evilList.add(new Power("Dark force", 15, "You get pressured from the extreme evil.", 0.2));
        evilList.add(new Power("Evil smile", 3, "It looks so evil, yet cute at the same time", 0.6));
        BrawlerSys.addBrawler(new Enemy("Evil Cat", 100, "evil_cat.jpg", evilList));

        //Lenin Cat
        ArrayList<Power> leninList = new ArrayList();
        leninList.add(new Power("Communism", 5, "Everything is equal.", 0.5));
        leninList.add(new Power("Sing the Soviet Anthem", 99, "Show some respect.", 0.99));
        BrawlerSys.addBrawler(new Enemy("Lenin Cat", 100, "lenin_cat.jpg", leninList));

    }

    /**
     * unless you make them the same size wtf no logic but colors This method is
     * called from within the constructor to initialize the form. WARNING: Do
     * NOT modify this code. The content of this method is always regenerated by
     * the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Tatakai Brawlers");

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Create Brawler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Choose a name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton1)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (nameField.getText().equals("")) {
            errorLabel.setText("Please provide a name!");
        } else {
            if (BrawlerSys.displayBrawlers().isEmpty()) {
                initBrawlers();
            }
            errorLabel.setText("");
            this.setVisible(false);
            chooseFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (nameField.getText().equals("")) {
            errorLabel.setText("Please provide a name!");
        } else {
            if (BrawlerSys.displayBrawlers().isEmpty()) {
                initBrawlers();
            }
            errorLabel.setText("");
            charFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
